apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    concurrent = {{ .Values.concurrent }}
    check_interval = 30
    privileged = true
  entrypoint: |
    #!/bin/bash
    set -xe

    cp /scripts/config.toml /etc/gitlab-runner/

    # Register the runner
    /entrypoint register --non-interactive \
      --url "{{ .Values.gitlabURL }}" \
      --tag-list "{{ .Values.tagList }}" \
      --kubernetes-image "alpine:latest" \
      --kubernetes-namespace "{{ .Release.Namespace }}" \
      --executor kubernetes \
      --config "/etc/gitlab-runner/config.toml" \
      --locked=false \
      --run-untagged=false \
      --kubernetes-privileged=true \
      --description "{{ .Release.Name }} - {{ .Values.description }}" \
      --paused

    # Start the runner
    /entrypoint run --user=gitlab-runner \
      --working-directory=/home/gitlab-runner \
      --config "/etc/gitlab-runner/config.toml"