apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: gitlab-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-admin
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gitlab-admin
  apiGroup: rbac.authorization.k8s.io